name: sign_language
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.0
  camera: ^0.10.0+2
  permission_handler: ^10.2.0
  provider: ^6.0.3
  http: ^0.13.3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  video_player: ^2.5.1
  image: ^3.0.1
  collection: ^1.16.0
  tflite: ^1.1.2
  path_provider: ^2.0.9
  logger: ^1.1.0
  firebase_core: ^2.14.0  # Ensure this is a compatible version
  cloud_firestore: ^4.11.0  # Ensure this is a compatible version
  flutter_rating_bar: ^4.0.1  # Ensure this is up to date
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  firebase_analytics: ^10.2.0  # Ensure this matches your Firebase setup

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#FFA500"
  adaptive_icon_foreground: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img.png
    - assets/A.png
    - assets/B.png
    - assets/C.png
    - assets/D.png
    - assets/E.png
    - assets/F.png
    - assets/G.png
    - assets/H.png
    - assets/I.png
    - assets/J.png
    - assets/K.png
    - assets/L.png
    - assets/M.png
    - assets/N.png
    - assets/O.png
    - assets/P.png
    - assets/Q.png
    - assets/R.png
    - assets/S.png
    - assets/T.png
    - assets/U.png
    - assets/V.png
    - assets/W.png
    - assets/X.png
    - assets/Y.png
    - assets/Z.png
    - assets/background2.png
    - assets/img2.png
    - assets/loading2.gif
    - assets/letters/
    - assets/gif/
    - assets/ic_launcher.png
    - assets/goodbye.png
    - assets/no.png
    - assets/yes.png
    - assets/please.png
    - assets/thankyou.png
    - assets/videos/fsl.mp4
    - assets/videos/family.mp4
    - assets/videos/home.mp4
    - assets/videos/food.mp4
    - assets/videos/greetings.mp4
    - assets/videos/alphabet.mp4
    - assets/videos/beginner.mp4
    - assets/models3.tflite
    - assets/labels3.txt
    - assets/models2.tflite
    - assets/labels2.txt
    - assets/models1.tflite
    - assets/labels1.txt
    - assets/Hi.png
    - assets/GoodNoon.png
    - assets/GoodMorning.png
    - assets/GoodAfternoon.png
    - assets/GoodNight.png
    - assets/Hello.png
    - assets/name.png
    - assets/surname.png
    - assets/familyname.png
    - assets/nickname.png
    - assets/shortname.png
    - assets/age.png
